Epets/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^app/', include('app.urls', namespace='app')),
]

app/urls.py
#coding=utf-8
from django.conf.urls import url

from app import views

urlpatterns = [
    # 主页
    url(r'^homepage/(\d+)/$', views.homepage, name='homepage'),
    # 主页
    url(r'^homepage/$', views.homepage1, name='homepage1'),
    # 购物车
    url(r'^shopcar/$', views.shopcar, name='shopcar'),
    # 商品详情一
    url(r'^goodsdetail/(\d+)/$', views.goodsdetail, name='goodsdetail'),
    # 商品详情二
    url(r'^goodsdetail2/(\d+)/$', views.goodsdetail2, name='goodsdetail2'),
    # 注册
    url(r'^register/$', views.register, name='register'),
    # 登录
    url(r'^login/$', views.login, name='login'),
    # 注销
    url(r'^logout/$', views.logout, name='logout'),
    # 添加到购物车
    url(r'^addshopcar/$', views.addshopcar, name='addshopcar'),
    # 从购物车移除
    url(r'^delshopcar/$', views.delshopcar, name='delshopcar'),
    # 修改选中状态
    url(r'^changestatus/$', views.changestatus, name='changestatus'),
    # 全选或取消全选
    url(r'^changeisall/$', views.changeisall, name='changeisall'),
    # 生产订单号
    url(r'^generateorder/$', views.generateorder, name='generateorder'),
    # 订单详情
    url(r'^orderdetail/(\d+)/$', views.orderdetail, name='orderdetail'),
    # 用户全部订单
    url(r'^orderlist/$', views.orderlist, name='orderlist'),
    # 支付完成,通知服务器
    url(r'^appnotify/$', views.appnotify, name='appnotify'),
    # 支付完成，客户端从支付页面返回项目页面
    url(r'^returnview/$', views.returnview, name='returnview'),
    # 支付
    url(r'^pay/$', views.pay, name='pay'),
]

app/models.py
#coding=utf-8
from django.db import models


# 轮播图
class Banner(models.Model):
    img = models.CharField(max_length=100)

# 用户
class User(models.Model):
    name = models.CharField(max_length=40, unique=True)
    email = models.CharField(max_length=40)
    password = models.CharField(max_length=40)
    token = models.CharField(max_length=256)

# 天天惊喜
class DailySurprise(models.Model):
    img = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    price = models.CharField(max_length=20)
    preprice = models.CharField(max_length=20)
    activity = models.CharField(max_length=20)
    span = models.CharField(max_length=20)


# 精品推荐
class Recommendation(models.Model):
    img = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    price = models.CharField(max_length=20)
    reason = models.CharField(max_length=20)
    p = models.CharField(max_length=100)


# 商品展示
class Goods(models.Model):
    img = models.CharField(max_length=100)
    name = models.CharField(max_length=100)
    price = models.CharField(max_length=20)


# 购物车
class Shopcar(models.Model):
    user = models.ForeignKey(User)
    goods = models.ForeignKey(DailySurprise)
    num = models.IntegerField()
    is_select = models.BooleanField(default=True)


# 用户订单（关联用户和订单）
class Order(models.Model):
    # 关联用户
    user = models.ForeignKey(User)
    # 订单创建时间
    createtime = models.DateTimeField(auto_now_add=True)
    # 记录状态（-1过期、未付款0、已付款1，未发货2、待收货3...）
    status = models.IntegerField(default=0)
    # 订单号
    identifier = models.CharField(max_length=256)


# 商品订单（关联商品和订单）
class OrderGoods(models.Model):
    # 订单
    order = models.ForeignKey(Order)
    # 商品
    goods = models.ForeignKey(DailySurprise)
    # 个数
    number = models.IntegerField()

templates/login.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>登录</title>

    <link rel="stylesheet" href="{% static 'css/login.css' %}"/>

    <script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>

</head>
<body>
<div class="login_head">
    <div class="loginh_con">
        <div class="loginh_left">
            <img src="{% static 'img/register/QQ图片20160909171624_23.gif' %}"/>
        </div>
        <div class="loginh_right">
            <ul>
                <li><a href="#">E宠商城</a></li>
                <li><a href="#">活动</a></li>
                <li><a href="#">品牌</a></li>
            </ul>
        </div>
    </div>
</div>

<div class="login_middle">
    <div class="login">
        <div class="login_con">
            <div class="login_main">
                <div class="login_tab">
                    <p><a href="{% url 'app:homepage' 0 %}"> 首页 </a></p>
                    <p><a href="{% url 'app:register' %}"> 无账号,去注册 </a></p>
                </div>
                <form action="{% url 'app:login' %}" method="post">
                    {% csrf_token %}
                    <div class="login_input">
                        <div class="text">
                            <span></span>
                            <input type="text" placeholder="用户名" name="name"/>
                        </div>
                        <div class="pwd">
                            <span></span>
                            <input type="password" placeholder="密码" name="password"/>
                        </div>
                    </div>
                    {% if err %}
                        <p style="color: red">{{ err }}</p>
                    {% endif %}
                    <div class="check">
							<span>
								<input type="checkbox"/>
								<i>自动登录</i>
							</span>
                        <a href="#">忘记密码?</a>
                    </div>
                    <div class="btn">
                        <input type="submit" value="登录"/>
                    </div>
                </form>


                <div class="link">
							<span>
								<h5>合作网站登录：</h5>
								<img src="{% static 'img/register/QQ截图20160920134847.png' %}"/>
							</span>

                    <a href="#">注册账号</a>
                </div>


            </div>
        </div>
    </div>
</div>

<div class="login_footer">
    <div class="footer_list">
        <ul>
            <li><a href="#">E宠商城</a></li>
            <li><a href="#">淘宝</a></li>
            <li><a href="#">知识</a></li>
            <li><a href="#">联系我们</a></li>
            <li><a href="#">关于我们</a></li>
            <li><a href="#">游戏</a></li>
        </ul>
        <p>渝ICP备13005525号-2 渝ICP备 10002905 增值电信业务经营许可证：渝B2-20140042 Copyright &copy; 2007-2016 epet.com 重庆易宠科技有限公司</p>
    </div>
</div>


</body>
</html>

templates/orderdetail.html
{% load static %}
<!DOCTYPE html>
<html>
<head>

    <meta charset="utf-8"/>
    <title>E宠物 | 订单详情</title>
    <link rel="stylesheet" href="{% static 'css/common.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/orderdetail.css' %}"/>

    <script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/orderdetail.js' %}"></script>


</head>
<body>

<!--头部开始-->
<div class="header">
    <div class="header_con">
        <div class="header_left">
		 			<span>
			 			<a href="#" class="header_a">E宠就是正品</a>
			 			<i>评价(<a href="#">389.4万</a>)</i>
		 		    </span>
        </div>
        <div class="header_right">
            <ul>
                {% if name %}
                    <li style="color: #007aff">用户: {{ name }}</li>
                    <li><a href="{% url 'app:logout' %}">退出</a></li>
                    <li><a href="{% url 'app:orderlist' %}">全部订单</a></li>
                {% else %}
                    <div>
                        <li><a href="{% url 'app:login' %}">[登录]</a></li>
                        <li><a href="{% url 'app:register' %}">[注册]</a></li>
                    </div>
                {% endif %}
                <li style="background: none"><a href="{% url 'app:homepage' 0 %}">首页</a></li>
                <li id="mypet" style="background: none">

                    <div class="mypet">
                        <a href="#">我的订单 </a>
                        <a href="#">充值得到优惠</a>
                        <a href="#">兑换现金劵</a>
                        <a href="#">推荐得惊喜</a>
                    </div>
                </li>
                <li id="mycollect">
                    <a href="#">收藏我 <img src="{% static 'img/common_img/h5.gif' %}"></a>
                    <div class="mycollect">
                        <input type="button" value="加入收藏夹" class="join">
                        <input type="button" value="保存到桌面" class="save">
                    </div>
                </li>
                <li><a href="#" class="lastli">投诉建议</a></li>
            </ul>
        </div>
    </div>
</div>
<!--头部结束-->

<div class="shopcar_con">
    <div class="head">
        <div class="logo">
            <img src="{% static 'img/shopcar/cart-logo.png' %}">
            <span>订单详情</span>
        </div>
        <div class="search">
            <input type="text" class="searchinput">
            <input type="button" value="搜索" class="searchbtn">
        </div>
    </div>
</div>

<div class="ending">
    {#    <div class="end-left"><a href="#"><span>取消订单</span></a></div>#}
    <a href="#">
        <div class="end-left">
            <h3>订单详情: {{ order.identifier }}</h3>
        </div>
    </a>

    <div class="end-right" orderid="{{ order.id }}">
        {% if order == 0 %}
            <span>去结账</span>
        {% else %}
            <a href="{% url 'app:homepage' 0 %}">继续购物</a>
        {% endif %}
    </div>

</div>

<ul class="shopcar_list">
    <li>
        <div><p>用户</p></div>
        <div><p>订单号</p></div>
        <div><p>订单创建时间</p></div>
        <div><p>订单状态</p></div>
    </li>
    <li>
        <div><p>{{ order.user.name }}</p></div>
        <div><p>{{ order.identifier }}</p></div>
        <div><p>{{ order.createtime }}</p></div>
        <div>
            {#            <span style="float: left; margin-left: 20px">￥{{ totalprice }}</span>#}
            {#            <span style="float: right; margin-right: 20px">{{ order.status }}</span>#}
            <p style="color: red;">
                {% if order.status == -1 %}
                    订单超时
                {% elif order.status == 0 %}
                    待支付
                {% elif order.status == 1 %}
                    待发货
                {% elif order.status == 2 %}
                    待收货
                {% elif order.status == 2 %}
                    待评价
                {% else %}
                    退货/退款
                {% endif %}
            </p>
        </div>
    </li>
</ul>

<ul class="list_ul">
    {% for ordergoods in order.ordergoods_set.all %}
        <li class="imgs">
            <div class="forloop">{{ forloop.counter }}</div>
            <div><img src="{{ ordergoods.goods.img }}" alt=""></div>
            <div class="units">
                <p>名称: {{ ordergoods.goods.name }}</p>
                <p class="unitprice">单价: ￥{{ ordergoods.goods.price }}</p>
                <p class="unit">数量: {{ ordergoods.number }}</p>
            </div>
        </li>
    {% endfor %}
</ul>


<!--尾部开始-->
<div class="footer">
    <div class="footer_top">
        <div class="top_list">
            <ul>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_03.gif' %}">
                    <p>绝对正品</p>
                </li>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_05.gif' %}">
                    <p>全球的好货</p>
                </li>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_07.gif' %}">
                    <p>自家的仓库</p>
                </li>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_09.gif' %}">
                    <p>自家的配送</p>
                </li>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_11.gif' %}">
                    <p>养宠的帮手</p>
                </li>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_13.gif' %}">
                    <p>小小的成绩</p>
                </li>
            </ul>
        </div>

        <div class="bottom_list">
            <div class="bot_left">
                <h5><img src="{% static 'img/common_img/QQ图片20160909175522_22.gif' %}"></h5>
                <div class="left_con">
                    <h3>服务热线：</h3>
                    <p>400-888-9200<span>（免长途费）</span></p>
                    <i>023-65584888</i>
                    <em>工作时间：9：00-21：00</em>
                </div>
            </div>
            <div class="bot_right">
                <ul class="list_right">
                    <li>
                        <h2>支付方式</h2>
                        <div class="con_list">
                            <a href="#">货到付款</a>
                            <a href="#">余额支付</a>
                            <a href="#">银行转账</a>
                            <a href="#">在线支付</a>
                        </div>
                    </li>
                    <li>
                        <h2>配送方式</h2>
                        <div class="con_list">
                            <a href="#">E宠快递</a>
                            <a href="#">外包快递</a>
                            <a href="#">物流运输</a>
                            <a href="#">公司地址</a>
                        </div>
                    </li>
                    <li>
                        <h2>购物指南</h2>
                        <div class="con_list">
                            <a href="#">退换货政策</a>
                            <a href="#">它时尚杂志</a>
                            <a href="#">常见问题</a>
                            <a href="#">宠物知识</a>
                        </div>
                    </li>
                    <li>
                        <h2>关于我们</h2>
                        <div class="con_list">
                            <a href="#">关于我们</a>
                            <a href="#">仓储中心</a>
                            <a href="#">联系我们</a>
                            <a href="#">人才招聘</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="footer_mid">
    <div class="footer_midcon">
        <div class="mid_left">
            <div class="safe">
							<span>
								<i></i>
								<h5>安全认证</h5>
								<b></b>
							</span>
            </div>
            <div class="safeSite">
                <img src="{% static 'img/common_img/safe360.png' %}">
                <img src="{% static 'img/common_img/bottom_small_img.png' %}">
                <img src="{% static 'img/common_img/safegs.png' %}">
                <img src="{% static 'img/common_img/safeqq.png' %}">
                <img src="{% static 'img/common_img/safesite.png' %}">
                <img src="{% static 'img/common_img/safetrace.png' %}">

            </div>
        </div>
        <div class="mid_center">
            <div class="two-code1">
                <p>扫描或点击下载手机版</p>
                <img src="{% static 'img/common_img/QQ图片20160909175522_26.gif' %}">
            </div>
            <div class="two-code2">
                <p>扫描或点击下载手机版</p>
                <img src="{% static 'img/common_img/QQ图片20160909175522_26.gif' %}">
            </div>
        </div>
        <div class="mid_right">
            <div class="honour">
							<span>
								<i></i>
								<h5>荣誉奖章</h5>
								<b></b>
							</span>
            </div>
            <div class="honourSite">
                <img src="{% static 'img/common_img/ebrun.png' %}">
                <img src="{% static 'img/common_img/wsxh.png' %}">
                <img src="{% static 'img/common_img/cqsywyh.png' %}">
                <img src="{% static 'img/common_img/goodNet.png' %}">
                <img src="{% static 'img/common_img/cqsapa.png' %}">
                <img src="{% static 'img/common_img/sjws.png' %}">

            </div>
        </div>
    </div>
</div>

<div class="footer_bottom">
    <p>渝ICP13005525号-2 &nbsp;&nbsp; 渝ICP备10002905 &nbsp;&nbsp;&nbsp; 增值电信业务经营许可证：渝B2-20140042 &nbsp;&nbsp; Copyright
        ©&nbsp;
        2007-2016epet.com&nbsp; &nbsp;重庆易宠科技有限公司</p>
</div>

<!--尾部结束-->

</body>
</html>

templates/orderlist.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <title>E宠物 | 订单表</title>
    <link rel="stylesheet" href="{% static 'css/common.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/orderdetail.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/orderlist.css' %}"/>

</head>
<body>

<!--头部开始-->
<div class="header">
    <div class="header_con">
        <div class="header_left">
		 			<span>
			 			<a href="#" class="header_a">E宠就是正品</a>
			 			<i>评价(<a href="#">389.4万</a>)</i>
		 		    </span>
        </div>
        <div class="header_right">
            <ul>
                {% if name %}
                    <li style="color: #007aff">用户: {{ name }}</li>
                    <li><a href="{% url 'app:logout' %}">退出</a></li>
                    <li><a href="{% url 'app:shopcar' %}">购物车</a></li>
                {% else %}
                    <div>
                        <li><a href="{% url 'app:login' %}">[登录]</a></li>
                        <li><a href="{% url 'app:register' %}">[注册]</a></li>
                    </div>
                {% endif %}
                <li style="background: none"><a href="{% url 'app:homepage' 0 %}">首页</a></li>
                <li id="mypet" style="background: none">
                    <div class="mypet">
                        <a href="#">我的订单 </a>
                        <a href="#">充值得到优惠</a>
                        <a href="#">兑换现金劵</a>
                        <a href="#">推荐得惊喜</a>
                    </div>
                </li>
                <li id="mycollect">
                    <a href="#">收藏</a>
                    <div class="mycollect">
                        <input type="button" value="加入收藏夹" class="join">
                        <input type="button" value="保存到桌面" class="save">
                    </div>
                </li>
                <li><a href="#" class="lastli">投诉建议</a></li>
            </ul>
        </div>
    </div>
</div>
<!--头部结束-->

<div class="shopcar_con">
    <div class="head">
        <div class="logo">
            <img src="{% static 'img/shopcar/cart-logo.png' %}">
            <span>全部订单</span>
        </div>
        <div class="search">
            <input type="text" class="searchinput">
            <input type="button" value="搜索" class="searchbtn">
        </div>
    </div>
</div>

<div class="ending">
    {#    <div class="end-left"><a href="#"><span>取消订单</span></a></div>#}
    <a href="#">
        <div class="end-left">
            <h3>用户名:&nbsp&nbsp&nbsp&nbsp;{{ name }}</h3>
        </div>
    </a>
    <a href="#">
        <div class="end-right">
            {#        <span>去结账</span>#}
        </div>
    </a>
</div>

<ul class="shopcar_list">
    <li>
        <div><p>订单号</p></div>
        <div><p>订单创建时间</p></div>
        <div><p>订单状态</p></div>
        <div><p>备注</p></div>
    </li>

    {% for order in orders %}
        <li>
            <a href="{% url 'app:orderdetail' order.id %}">
                <div><p>{{ order.identifier }}</p></div>
            </a>
            <div><p>{{ order.createtime }}</p></div>
            <a href="{% url 'app:orderdetail' order.id %}">
                <div><p style="color: red;line-height: 50px">
                {% if order.status == -1 %}
                    订单超时
                {% elif order.status == 0 %}
                    待支付
                {% elif order.status == 1 %}
                    待发货
                {% elif order.status == 2 %}
                    待收货
                {% elif order.status == 2 %}
                    待评价
                {% else %}
                    退货/退款
                {% endif %}
            </p></div>
            </a>
            <div><p>...</p></div>
        </li>
    {% endfor %}

</ul>


<!--尾部开始-->
<div class="footer">
    <div class="footer_top">
        <div class="top_list">
            <ul>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_03.gif' %}">
                    <p>绝对正品</p>
                </li>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_05.gif' %}">
                    <p>全球的好货</p>
                </li>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_07.gif' %}">
                    <p>自家的仓库</p>
                </li>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_09.gif' %}">
                    <p>自家的配送</p>
                </li>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_11.gif' %}">
                    <p>养宠的帮手</p>
                </li>
                <li>
                    <img src="{% static 'img/common_img/QQ图片20160909175522_13.gif' %}">
                    <p>小小的成绩</p>
                </li>
            </ul>
        </div>

        <div class="bottom_list">
            <div class="bot_left">
                <h5><img src="{% static 'img/common_img/QQ图片20160909175522_22.gif' %}"></h5>
                <div class="left_con">
                    <h3>服务热线：</h3>
                    <p>400-888-9200<span>（免长途费）</span></p>
                    <i>023-65584888</i>
                    <em>工作时间：9：00-21：00</em>
                </div>
            </div>
            <div class="bot_right">
                <ul class="list_right">
                    <li>
                        <h2>支付方式</h2>
                        <div class="con_list">
                            <a href="#">货到付款</a>
                            <a href="#">余额支付</a>
                            <a href="#">银行转账</a>
                            <a href="#">在线支付</a>
                        </div>
                    </li>
                    <li>
                        <h2>配送方式</h2>
                        <div class="con_list">
                            <a href="#">E宠快递</a>
                            <a href="#">外包快递</a>
                            <a href="#">物流运输</a>
                            <a href="#">公司地址</a>
                        </div>
                    </li>
                    <li>
                        <h2>购物指南</h2>
                        <div class="con_list">
                            <a href="#">退换货政策</a>
                            <a href="#">它时尚杂志</a>
                            <a href="#">常见问题</a>
                            <a href="#">宠物知识</a>
                        </div>
                    </li>
                    <li>
                        <h2>关于我们</h2>
                        <div class="con_list">
                            <a href="#">关于我们</a>
                            <a href="#">仓储中心</a>
                            <a href="#">联系我们</a>
                            <a href="#">人才招聘</a>
                        </div>
                    </li>
                </ul>
            </div>
        </div>
    </div>
</div>

<div class="footer_mid">
    <div class="footer_midcon">
        <div class="mid_left">
            <div class="safe">
							<span>
								<i></i>
								<h5>安全认证</h5>
								<b></b>
							</span>
            </div>
            <div class="safeSite">
                <img src="{% static 'img/common_img/safe360.png' %}">
                <img src="{% static 'img/common_img/bottom_small_img.png' %}">
                <img src="{% static 'img/common_img/safegs.png' %}">
                <img src="{% static 'img/common_img/safeqq.png' %}">
                <img src="{% static 'img/common_img/safesite.png' %}">
                <img src="{% static 'img/common_img/safetrace.png' %}">

            </div>
        </div>
        <div class="mid_center">
            <div class="two-code1">
                <p>扫描或点击下载手机版</p>
                <img src="{% static 'img/common_img/QQ图片20160909175522_26.gif' %}">
            </div>
            <div class="two-code2">
                <p>扫描或点击下载手机版</p>
                <img src="{% static 'img/common_img/QQ图片20160909175522_26.gif' %}">
            </div>
        </div>
        <div class="mid_right">
            <div class="honour">
							<span>
								<i></i>
								<h5>荣誉奖章</h5>
								<b></b>
							</span>
            </div>
            <div class="honourSite">
                <img src="{% static 'img/common_img/ebrun.png' %}">
                <img src="{% static 'img/common_img/wsxh.png' %}">
                <img src="{% static 'img/common_img/cqsywyh.png' %}">
                <img src="{% static 'img/common_img/goodNet.png' %}">
                <img src="{% static 'img/common_img/cqsapa.png' %}">
                <img src="{% static 'img/common_img/sjws.png' %}">

            </div>
        </div>
    </div>
</div>

<div class="footer_bottom">
    <p>渝ICP13005525号-2 &nbsp;&nbsp; 渝ICP备10002905 &nbsp;&nbsp;&nbsp; 增值电信业务经营许可证：渝B2-20140042 &nbsp;&nbsp; Copyright
        ©&nbsp;
        2007-2016epet.com&nbsp; &nbsp;重庆易宠科技有限公司</p>
</div>

<!--尾部结束-->

</body>
</html>

templates/register.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>注册</title>

    <link rel="stylesheet" href=""/>
    <link rel="stylesheet" href="{% static 'css/register.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/register.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/jquery.idcode.css' %}"/>

    <script type="text/javascript" src="{% static 'js/jquery-1.12.3.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.cookie.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/jquery.idcode.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/register.js' %}"></script>

</head>
<body>

<div class="register_head">
    <div class="registerh_con">
        <div class="registerhc_left">
            <span class="logo"><img src="{% static 'img/register/QQ图片20160909171624_23.gif' %}"></span>
            <span class="register"><img src="{% static 'img/register/welcome_07.jpg' %}">	</span>
        </div>
        <div class="registerhc_right">

        </div>
    </div>
</div>

<div class="register_middle">
    <div class="registerm_con">
        <div class="login">
            <div class="text">
                <p id="p1"><a href="{% url 'app:homepage' 0 %}">首页</a></p>
                <p id="p2"><a href="{% url 'app:login' %}">已有账号,去登录</a></p>
            </div>
            <form action="{% url 'app:register' %}" method="post">
                {% csrf_token %}

                <div class="text">
                    <span>用户名：</span>
                    <input type="text" placeholder="用户名(6~12),字母(大小写),数字" id="name" maxlength="12" name="name">
                    <span class='hint' style="color: red;">格式错误</span>
                    <span style="color: red;">{{ err1 }}</span>
                </div>

                <div class="text">
                    <span>邮箱：</span>
                    <input type="text" placeholder="邮箱" id="email" name="email">
                    <span class='hint' style="color: red;">格式错误</span>
                </div>

                <div class="text">
                    <span>设置密码：</span>
                    <input type="password" placeholder="密码(6~12),字母/数字..." id='password1' maxlength="12" name="password1">
                    <span class='hint' style="color: red;">格式错误</span>
                </div>

                <div class="text">
                    <span>验证密码：</span>
                    <input type="password" placeholder="再次输入密码" maxlength="12" id='password2' name="password2">
                    <span class='hint' style="color: red;">密码不一致</span>
                </div>

                <div class="text">
                    <span></span>
                    <input type="submit" value="注册">
                </div>

            </form>
        </div>
    </div>
</div>


<div class="registery_footer">
    <div class="footer_list">
        <ul>
            <li><a href="#">E宠商城</a></li>
            <li><a href="#">淘宝</a></li>
            <li><a href="#">知识</a></li>
            <li><a href="#">联系我们</a></li>
            <li><a href="#">关于我们</a></li>
            <li><a href="#">游戏</a></li>
        </ul>
        <p>渝ICP备13005525号-2 渝ICP备 10002905 增值电信业务经营许可证：渝B2-20140042 Copyright © 2007-2016 epet.com 重庆易宠科技有限公司</p>
    </div>
</div>


</body>
</html>